name: Continuous Integration

on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        # Maps port 6379 on service container to the host
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: yarn install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install

      - run: yarn test
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          LND_HOST: ${{ secrets.LND_HOST }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          LND_MACAROON_READ_ONLY: ${{ secrets.LND_MACAROON_READ_ONLY }}
          LND_MACAROON_INVOICE: ${{ secrets.LND_MACAROON_INVOICE }}
          LND_MACAROON_ADMIN: ${{ secrets.LND_MACAROON_ADMIN }}
          DALLE_API_KEY: ${{ secrets.DALLE_API_KEY }}

      - name: Get test coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
