name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: yarn install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install

      - run: yarn test
        env:
          HOST: ${{ secrets.HOST }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          READ_ONLY_MACAROON: ${{ secrets.READ_ONLY_MACAROON }}
          INVOICE_MACAROON: ${{ secrets.INVOICE_MACAROON }}
          ADMIN_MACAROON: ${{ secrets.ADMIN_MACAROON }}
          DALLE_API_KEY: ${{ secrets.DALLE_API_KEY }}

      - name: Get test coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
